using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Synthesis.States;
using System.Text;
using System.Text.Json;
using System.IO;
using System.Linq;
using Noggog;

namespace FarmAnimalOwnershipProject
   

{   // Classes //
    public class UserSettings
    {
        // Whether to enable verbose logging (kept for compatibility)
        public bool EnableLogging { get; set; } = false;

        // The animal races we are looking for
        public string[] IncludeRaceTerms { get; set; } = new[]
        {
            "Goat", "Chicken", "Cow", "Horse", "Pig", "Sheep", "Dog", "Cat", "Bunny", "Husky"
        };

        // Animal names we want to exclude
        public string[] ExcludeNameTerms { get; set; } = new[]
        {
            "Wild", "Bandit", "Forsworn", "Sabre", "Pigeon", "Zombie", "Draugr", "Durzog"
        };

        // Plugin exclusion patterns (wildcards supported)
        public string[] ExcludePlugins { get; set; } = new[]
        {
            "Vigilant.esm", "*FollowerFramework*", "*SkyrimUnderground*", "*HearthFire*", "cc*"
        };

        // Cell exclusion patterns (wildcards supported)
        public string[] ExcludeCellRules { get; set; } = new[]
        {
            "BYOH*"
        };
    }

    public class Program
    {
        public static class FarmAnimalOwnershipPatcher
        {
            // Current settings instance (populated by Synthesis UI)
            private static UserSettings Settings = new UserSettings();
            // Autogenerated settings container populated by Synthesis when available
            private static Lazy<PatcherSettings>? AutogeneratedSettings = null;


            // Custom divider and printout function for readability
            private static bool _lastWasDivider = false;

            private static void PrintDivider()
            {
                if (_lastWasDivider) return;
                Console.WriteLine("----------------------------------------------------------------------------------------------------------------------------------------");
                _lastWasDivider = true;
            }

            private static void PrintShortDivider()
            {
                if (_lastWasDivider) return;
                Console.WriteLine("--------------------------------------------------------------------");
                _lastWasDivider = true;
            }

            private static void ConsoleWriteLine(string text)
            {
                Console.WriteLine(text);
                _lastWasDivider = false;
            }

            // Helper function to add skipped animals to the dictionary
            private static void AddSkip(
                Dictionary<string, List<(string Animal, string Plugin, string Reason)>> dict,
                string animal,
                string plugin,
                string cellEdid,
                string reason)
            {
                string key = cellEdid ?? "(unknown cell)";

                if (!dict.TryGetValue(key, out var list))
                {
                    list = new List<(string Animal, string Plugin, string Reason)>();
                    dict[key] = list;
                }

                list.Add((animal, plugin, reason));
                }
               
        
            // Wildcard-aware plugin exclusion
            private static bool IsPluginExcluded(string pluginName)
            {
                foreach (var pattern in Settings.ExcludePlugins)
                {
                    // Convert wildcard pattern to regex
                    string regexPattern = "^" +
                        System.Text.RegularExpressions.Regex.Escape(pattern)
                        .Replace("\\*", ".*")
                        .Replace("\\?", ".") +
                        "$";

                    if (System.Text.RegularExpressions.Regex.IsMatch(
                            pluginName, regexPattern, System.Text.RegularExpressions.RegexOptions.IgnoreCase))
                    {
                        return true;
                    }
                }
            
                return false;
            }
            private static bool RuleMatchesCell(string rule, string cellEdid) // align
            {
                string regexPattern = "^" +
                    System.Text.RegularExpressions.Regex.Escape(rule)
                    .Replace("\\*", ".*")
                    .Replace("\\?", ".") +
                    "$";

                return System.Text.RegularExpressions.Regex.IsMatch(
                    cellEdid, regexPattern, System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            }

            // Parse semicolon-separated list from UI settings
            private static string[] ParseList(string value)
            {
                if (string.IsNullOrWhiteSpace(value))
                    return Array.Empty<string>();

                return value.Split(';', StringSplitOptions.RemoveEmptyEntries)
                    .Select(s => s.Trim())
                    .Where(s => !string.IsNullOrEmpty(s))
                    .ToArray();
            }

            // Overload that accepts settings injected by newer Synthesis versions (if available).
            // This method will be picked up if you call AddPatch with a settings type.
            public static Task RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, PatcherSettings synthSettings)
            {
                if (synthSettings != null)
                {
                    var include = ParseList(synthSettings.IncludeRaceTerms);
                    if (include.Length > 0)
                        Settings.IncludeRaceTerms = include;

                    var excludeNames = ParseList(synthSettings.ExcludeNameTerms);
                    if (excludeNames.Length > 0)
                        Settings.ExcludeNameTerms = excludeNames;

                    var excludePlugins = ParseList(synthSettings.ExcludePlugins);
                    if (excludePlugins.Length > 0)
                        Settings.ExcludePlugins = excludePlugins;

                    var excludeCells = ParseList(synthSettings.ExcludeCellRules);
                    if (excludeCells.Length > 0)
                        Settings.ExcludeCellRules = excludeCells;

                    Settings.EnableLogging = synthSettings.EnableLogging;
                }

                return RunPatch(state);
            }

                        // Main entry point for the patcher
            public static async Task Main(string[] args)
            {
                await SynthesisPipeline.Instance
                    .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                    .SetAutogeneratedSettings(nickname: "Patcher Settings", path: "FarmAnimalOwnershipSettings.json", out AutogeneratedSettings)
                    .SetTypicalOpen(GameRelease.SkyrimSE, "FarmAnimalOwnership.esp")
                    .Run(args);
            }

            // Location categories
            public enum LocationCategory
            {
                Town, Farm, Unknown, Mill, Wilderness, Stable
            }

            // Main patching logic
            public static Task RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
            {
                // Note: Settings are registered with Synthesis via AddSettings<UserSettings>().
                // Some Synthesis versions automatically inject settings into the patch function;
                // if your Synthesis version supports passing settings, we can accept a second
                // parameter here. For compatibility, this implementation uses the static
                // Settings instance (defaults or previously populated).

                // Attempt to load settings from a JSON file placed alongside the executable.
                // First, if Synthesis populated autogenerated settings, use them (UI settings).
                if (AutogeneratedSettings != null)
                {
                    try
                    {
                        var synthSettings = AutogeneratedSettings.Value;
                        if (synthSettings != null)
                        {
                            var include = ParseList(synthSettings.IncludeRaceTerms);
                            if (include.Length > 0)
                                Settings.IncludeRaceTerms = include;

                            var excludeNames = ParseList(synthSettings.ExcludeNameTerms);
                            if (excludeNames.Length > 0)
                                Settings.ExcludeNameTerms = excludeNames;

                            var excludePlugins = ParseList(synthSettings.ExcludePlugins);
                            if (excludePlugins.Length > 0)
                                Settings.ExcludePlugins = excludePlugins;

                            var excludeCells = ParseList(synthSettings.ExcludeCellRules);
                            if (excludeCells.Length > 0)
                                Settings.ExcludeCellRules = excludeCells;

                            Settings.EnableLogging = synthSettings.EnableLogging;
                        }
                    }
                    catch
                    {
                        // ignore errors reading autogenerated settings and fall back to file
                    }
                }

                // This is a fallback for Synthesis versions that do not provide AddSettings UI
                // wiring. File name: "FarmAnimalOwnershipSettings.json"
                try
                {
                    var settingsPath = Path.Combine(AppContext.BaseDirectory, "FarmAnimalOwnershipSettings.json");
                    if (File.Exists(settingsPath))
                    {
                        var json = File.ReadAllText(settingsPath);
                        var fileSettings = JsonSerializer.Deserialize<UserSettings>(json, new JsonSerializerOptions
                        {
                            PropertyNameCaseInsensitive = true
                        });

                        if (fileSettings != null)
                        {
                            // Merge non-null arrays from file into the runtime Settings
                            if (fileSettings.IncludeRaceTerms is not null)
                                Settings.IncludeRaceTerms = fileSettings.IncludeRaceTerms;
                            if (fileSettings.ExcludeNameTerms is not null)
                                Settings.ExcludeNameTerms = fileSettings.ExcludeNameTerms;
                            if (fileSettings.ExcludePlugins is not null)
                                Settings.ExcludePlugins = fileSettings.ExcludePlugins;
                            if (fileSettings.ExcludeCellRules is not null)
                                Settings.ExcludeCellRules = fileSettings.ExcludeCellRules;
                            Settings.EnableLogging = fileSettings.EnableLogging;
                        }
                    }
                }
                catch
                {
                    // Ignore errors reading settings file; proceed with defaults.
                }


                PrintShortDivider();
                ConsoleWriteLine("PATCHING...".PadLeft(50));
                PrintShortDivider();

                // Faction dictionary
                var factionsByEdid = new Dictionary<string, IFactionGetter>();
                foreach (var fac in state.LoadOrder.PriorityOrder.Faction().WinningOverrides())
                {
                    if (fac.EditorID != null)
                        factionsByEdid.TryAdd(fac.EditorID, fac);
                }

                // Keep track of seen NPCs to avoid duplicates
                var seen = new HashSet<FormKey>();

                // Dictionaries to track patched and skipped animals by cell
                var patchedAnimalsByCell = new Dictionary<string, List<(string Animal, string Plugin, string? OwnerFaction)>>();
                var skippedAnimalsByCell = new Dictionary<string, List<(string Animal, string Plugin, string Reason)>>();
                var excludedAnimalsByPlugin = new Dictionary<string, List<string>>();
                var excludedCellsByRule = new Dictionary<string, List<string>>();

                // Counters for summary
                int unknownCount = 0;
                int missingFactionCount = 0;
                int patchedCount = 0;
                int alreadyOwnedCount = 0;

                // Start of main
                // loops through all placed NPCs in the load order
                foreach (var context in state.LoadOrder.PriorityOrder.PlacedNpc().WinningContextOverrides(state.LinkCache))
                {
                    var placedNpc = context.Record;
                    var containingCell = FindContainingCell(context);
                    string cellEdid;

                    if (containingCell?.EditorID != null)
                    {
                        if (containingCell.EditorID.Contains("Wilderness", StringComparison.OrdinalIgnoreCase))
                            cellEdid = "Wilderness";
                        else
                            cellEdid = containingCell.EditorID;
                    }
                    else
                    {
                        cellEdid = "Wilderness"; // exterior cells with no EDID
                    }
                    {
                        if (!seen.Add(placedNpc.FormKey))
                            continue;
                    }
                    var npc = placedNpc.Base.TryResolve(state.LinkCache);
                    if (npc == null)
                        continue;

                    var animalLabel = npc.EditorID ?? "UnknownNPC";
                    var pluginName = placedNpc.FormKey.ModKey.FileName;
                    
                    // Wildcard-aware cell exclusion
                    bool cellExcluded = false;
                    foreach (var rule in Settings.ExcludeCellRules)
                    {
                        if (RuleMatchesCell(rule, cellEdid))
                        {
                            if (!excludedCellsByRule.TryGetValue(rule, out var cellList))
                            {
                                cellList = new List<string>();
                                excludedCellsByRule[rule] = cellList;
                            }

                            cellList.Add(cellEdid);
                            cellExcluded = true; // mark to skip this NPC
                            break;
                        }
                    }

                    if (cellExcluded)
                        continue;
                    // Wildcard-aware plugin exclusion
                    if (IsPluginExcluded(pluginName))
                    {
                            if (!excludedAnimalsByPlugin.TryGetValue(pluginName, out var list))
                            {
                                  list = new List<string>();
                                  excludedAnimalsByPlugin[pluginName] = list;
                            }

                             list.Add(animalLabel);
                             continue;
                    }


                    // Exclude other animals
                    if (!IsFarmAnimal(npc, state.LinkCache))
                        continue;

                    // Exclude owned animals
                    if (!placedNpc.Owner.IsNull)
                    {
                        alreadyOwnedCount++;
                        continue;
                    }

                    var location = containingCell?.Location.TryResolve(state.LinkCache);
                    var (category, matched) = CategorizeLocation(location, state.LinkCache, containingCell);

                    string combinedReason = "";

                    var townFaction = TryGetTownFaction(matched, factionsByEdid, containingCell);
                    if (townFaction == null)
                    {
                        combinedReason += "No suitable owner ";         // Location has no obvious owner faction
                        missingFactionCount++;
                    }

                    // Only unknown if BOTH category and matched are unknown
                    if (category == LocationCategory.Unknown && matched == null)
                    {
                        combinedReason += "and an unknown location";
                        unknownCount++;
                    }


                    if (combinedReason.Length > 0)
                    {
                        combinedReason = combinedReason.TrimEnd(' ', ' ');
                        AddSkip(skippedAnimalsByCell, animalLabel, pluginName, cellEdid, combinedReason);
                        continue;
                    }

                    var patchNpc = context.GetOrAddAsOverride(state.PatchMod);
                    patchNpc.Owner.SetTo(townFaction);
                    patchNpc.FactionRank = 0;
                    patchedCount++;

                    if (!patchedAnimalsByCell.TryGetValue(cellEdid, out var patchedList))
                    {
                        patchedList = new List<(string Animal, string Plugin, string? OwnerFaction)>();
                        patchedAnimalsByCell[cellEdid] = patchedList;
                    }

                    patchedList.Add((animalLabel, pluginName, townFaction?.EditorID));
                }   // End of main loop
                {
                    // Printout for patched animals by cell
                    PrintShortDivider();
                    ConsoleWriteLine("PATCHED BY CELL".PadLeft(50));
                    PrintShortDivider();
                    _lastWasDivider = false;
                    PrintDivider();

                    foreach (var kvp in patchedAnimalsByCell.OrderByDescending(k => k.Value.Count))
                    {
                        var cellLabel = kvp.Key;
                        var animals = kvp.Value;

                        var cellPlugin = animals
                            .Select(a => a.Plugin)
                            .Distinct()
                            .FirstOrDefault() ?? "(unknown plugin)";

                        ConsoleWriteLine($"{cellLabel}   ({animals.Count} patched)");

                        // Group by plugin first, then by animal+owner within each plugin.
                        var byPlugin = animals
                            .GroupBy(a => a.Plugin)
                            .Select(g => new
                            {
                                Plugin = g.Key,
                                Count = g.Count(),
                                Animals = g.ToList()
                            })
                            .OrderByDescending(p => p.Count);

                        foreach (var pluginGroup in byPlugin)
                        {
                            ConsoleWriteLine($"      [{pluginGroup.Plugin}]   ({pluginGroup.Count} patched)");

                            var byAnimal = pluginGroup.Animals
                                .GroupBy(a => new { a.Animal, a.OwnerFaction })
                                .Select(g => new
                                {
                                    g.Key.Animal,
                                    g.Key.OwnerFaction,
                                    Count = g.Count()
                                })
                                .OrderByDescending(a => a.Count);

                            foreach (var entry in byAnimal)
                            {
                                ConsoleWriteLine($"         {entry.Count} {entry.Animal}(s)   Is now owned by:  {entry.OwnerFaction}");
                            }
                        }

                        PrintDivider();
                    }

                    // Printout for skipped animals by cell
                    _lastWasDivider = false;
                    PrintShortDivider();
                    ConsoleWriteLine("SKIPPED BY CELL".PadLeft(50));
                    PrintShortDivider();
                    _lastWasDivider = false;
                    PrintDivider();

                    foreach (var kvp in skippedAnimalsByCell.OrderByDescending(k => k.Value.Count))
                    {
                        var cellLabel = kvp.Key;
                        var animals = kvp.Value;

                        ConsoleWriteLine($"{cellLabel} ({animals.Count} skipped)");

                        // Group by plugin first, then by animal+reason within each plugin.
                        var byPlugin = animals
                            .GroupBy(a => a.Plugin)
                            .Select(g => new
                            {
                                Plugin = g.Key,
                                Count = g.Count(),
                                Animals = g.ToList()
                            })
                            .OrderByDescending(p => p.Count);

                        foreach (var pluginGroup in byPlugin)
                        {
                            ConsoleWriteLine($"  [{pluginGroup.Plugin}] ({pluginGroup.Count} skipped)");

                            var byAnimal = pluginGroup.Animals
                                .GroupBy(a => new { a.Animal, a.Reason })
                                .Select(g => new
                                {
                                    g.Key.Animal,
                                    g.Key.Reason,
                                    Count = g.Count()
                                })
                                .OrderByDescending(a => a.Count);

                            foreach (var entry in byAnimal)
                            {
                                ConsoleWriteLine($"    {entry.Count}  -  {entry.Animal}   -   Returned:   {entry.Reason}");
                            }
                        }

                        PrintDivider();
                    }

                    // Printout for excluded animals by plugin
                    _lastWasDivider = false;
                    PrintShortDivider();
                    ConsoleWriteLine("EXCLUSION SUMMARY".PadLeft(50));
                    PrintShortDivider();

                    // Build combined list
                    var combined = new List<(string Rule, int Count, string Type)>();

                    // Plugin rules
                    var excludedPluginNames = excludedAnimalsByPlugin.Keys.ToList();
                    foreach (var rule in Settings.ExcludePlugins)
                    {
                        int count = excludedPluginNames
                            .Where(pluginName => RuleMatchesPlugin(rule, pluginName))
                            .Distinct()
                            .Count();

                        if (count > 0)
                            combined.Add((Rule: rule, Count: count, Type: "plugin"));
                    }

                    // Cell rules
                    foreach (var rule in Settings.ExcludeCellRules)
                    {
                        if (excludedCellsByRule.TryGetValue(rule, out var cells))
                        {
                            int count = cells.Distinct().Count();
                            if (count > 0)
                                combined.Add((Rule: rule, Count: count, Type: "cell"));
                        }
                    }

                    // Sort by count descending
                    foreach (var entry in combined.OrderByDescending(e => e.Count))
                    {
                        ConsoleWriteLine($"{entry.Rule} excluded {entry.Count} {entry.Type}(s)");
                    }



                    // Summary printout
                    _lastWasDivider = false;
                    PrintShortDivider();
                    ConsoleWriteLine("SUMMARY".PadLeft(50));
                    PrintShortDivider();

                    ConsoleWriteLine($"{patchedCount} Animals patched");
                    ConsoleWriteLine($"{alreadyOwnedCount} Animals already owned");
                    ConsoleWriteLine($"{missingFactionCount} Animals with no suitable owner");
                    ConsoleWriteLine($"{unknownCount} Animals in unknown locations");
                    PrintShortDivider();
                    return Task.CompletedTask;
                }
            }
            // Summary exclusion helper
            private static bool RuleMatchesPlugin(string rule, string pluginName)
            {
                string regexPattern = "^" +
                    System.Text.RegularExpressions.Regex.Escape(rule)
                    .Replace("\\*", ".*")
                    .Replace("\\?", ".") +
                    "$";

                return System.Text.RegularExpressions.Regex.IsMatch(
                    pluginName, regexPattern, System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            }

            // Helper function from "class FarmAnimalOwnershipPatcher"
            private static bool IsFarmAnimal(INpcGetter npc, ILinkCache<ISkyrimMod, ISkyrimModGetter> linkCache)
            {
                var npcEdid = npc.EditorID ?? "";

                if (Settings.ExcludeNameTerms.Any(term => npcEdid.Contains(term, StringComparison.OrdinalIgnoreCase)))
                    return false;

                var raceEdid = npc.Race.TryResolve(linkCache)?.EditorID ?? "";

                return Settings.IncludeRaceTerms.Any(term => raceEdid.Contains(term, StringComparison.OrdinalIgnoreCase));
            }

            // Dictionary for convention overrides for specific location to faction mappings
            // Since the naming conventions are not standardized I couldn't make a clean catch all solution
            private static readonly Dictionary<string, string> ConventionOverrides = new()
            {
                ["PelagiaFarmLocation"] = "PelagiaFarmFaction",
                ["HollyfrostFarmLocation"] = "HollyFrostFarmFaction",           // note the difference in capitalization
                ["HlaaluFarmLocation"] = "HlaaluFarmFaction",
                ["KatlasFarmLocation"] = "TownSolitudeFaction",                 // note how this location does not have their own faction
                ["ChillfurrowFarmLocation"] = "ChillfurrowFarmFaction",
                ["BrandyMugFarmLocation"] = "BrandyMugFarmFaction",
                ["BattleBornFarmLocation"] = "TownWhiterunFaction",
                ["DawnstarSanctuaryLocation"] = "DarkBrotherhoodFaction",
                ["DLC2SkaalVillageLocation"] = "DLC2SVGreathallFaction",        // note that the village has no town faction
                ["HalfmoonMillLocation"] = "HalfMoonMillFaction",
                ["MixwaterMillLocation"] = "MixwaterMillGilfreHouseFaction",    // note that the mill belongs to a house
                ["SolitudeSawmillLocation"] = "SolitudeSawmillFaction",
                ["BearsCaveMillLocation"] = "RG439BearsCaveMillFaction",        // note that modded locations/factions often use an added prefix or suffix
                ["DLC2RavenRockLocation"] = "DLC2RRBulwarkFaction",
                ["FrostRiverFarmLocation"] = "FrostRiverFarmFaction",
                ["KynesgroveFarmsLocationTGCoKG"] = "KynesgroveRagnasAndHerleifsHouseFactionTGCoKG",
                ["KynesgroveGalasSteadLocationTGCoKG"] = "KynesgroveGalasHouseFactionTGCoKG",
                ["RoriksteadLemkilsFarmLocation"] = "RoriksteadLemkilsFarmFaction"
            };

            // Dictionary for hold capital prefixes to faction mappings
            private static readonly Dictionary<string, string> HoldCapitalPrefixes = new()
            {
                ["Whiterun"] = "TownWhiterunFaction",
                ["Solitude"] = "TownSolitudeFaction",
                ["Riften"] = "TownRiftenFaction",
                ["Windhelm"] = "TownWindhelmFaction",
                ["Markarth"] = "TownMarkarthFaction",
                ["Falkreath"] = "TownFalkreathFaction",
                ["Morthal"] = "TownMorthalFaction",
                ["Dawnstar"] = "TownDawnstarFaction",
                ["Winterhold"] = "TownWinterholdFaction"
            };

            // Faction helper function
            private static IFactionGetter? TryGetTownFaction(
            ILocationGetter? location,
            Dictionary<string, IFactionGetter> factionsByEdid,
            ICellGetter? cell)
            {
                // 1. Convention overrides
                if (location?.EditorID != null &&
                    ConventionOverrides.TryGetValue(location.EditorID, out var overrideFactionEdid) &&
                    factionsByEdid.TryGetValue(overrideFactionEdid, out var overrideFaction))
                {
                    return overrideFaction;
                }

                // 2. Location-based TownXFaction
                if (location?.EditorID != null)
                {
                    var baseName = location.EditorID.EndsWith("Location")
                        ? location.EditorID[..^"Location".Length]
                        : location.EditorID;

                    var townCandidate = $"Town{baseName}Faction";

                    if (factionsByEdid.TryGetValue(townCandidate, out var faction))
                        return faction;
                }

                // 3. NEW: Cell-based hold-capital prefix detection
                if (cell?.EditorID != null)
                {
                    foreach (var kvp in HoldCapitalPrefixes)
                    {
                        if (cell.EditorID.StartsWith(kvp.Key, StringComparison.OrdinalIgnoreCase))
                        {
                            if (factionsByEdid.TryGetValue(kvp.Value, out var faction))
                                return faction;
                        }
                    }
                }

                return null;
            }


            // Cell helper function
            private static ICellGetter? FindContainingCell(
                IModContext<ISkyrimMod, ISkyrimModGetter, IPlacedNpc, IPlacedNpcGetter> context)
            {
                var current = context.Parent;
                while (current != null)
                {
                    if (current.Record is ICellGetter cell)
                        return cell;

                    current = current.Parent;
                }

                return null;
            }

            // Location helper function
            public static (LocationCategory category, ILocationGetter? matched)
            CategorizeLocation(ILocationGetter? location, ILinkCache<ISkyrimMod, ISkyrimModGetter> linkCache, ICellGetter? cell)
            {
                // 1. Location-based keyword detection
                if (location != null)
                {
                    var keywordEdids = location.Keywords?
                        .Select(k => k.TryResolve(linkCache)?.EditorID)
                        .Where(e => e != null)
                        .ToHashSet();

                    if (keywordEdids != null)
                    {
                        if (keywordEdids.Contains("LocTypeFarm"))
                            return (LocationCategory.Farm, location);

                        if (keywordEdids.Contains("LocTypeMill"))
                            return (LocationCategory.Mill, location);

                        if (keywordEdids.Contains("LocTypeSettlement")
                            || keywordEdids.Contains("LocTypeTown")
                            || keywordEdids.Contains("LocTypeCity")
                            || keywordEdids.Contains("LocTypeVillage"))
                            return (LocationCategory.Town, location);
                    }
                }

                // 2. Cell EditorID detection
                if (cell?.EditorID != null)
                {
                    var edid = cell.EditorID.ToLower();

                    if (edid.Contains("wilderness"))
                        return (LocationCategory.Wilderness, location);

                    if (edid.Contains("farm"))
                        return (LocationCategory.Farm, location);

                    if (edid.Contains("mill"))
                        return (LocationCategory.Mill, location);

                    if (edid.Contains("stable"))
                        return (LocationCategory.Farm, location);

                    if (edid.Contains("village") || edid.Contains("settlement") || edid.Contains("town"))
                        return (LocationCategory.Town, location);

                    // 3. NEW: Hold-capital prefix detection for city districts
                    foreach (var kvp in HoldCapitalPrefixes)
                    {
                        if (cell.EditorID.StartsWith(kvp.Key, StringComparison.OrdinalIgnoreCase))
                            return (LocationCategory.Town, location);
                    }
                }

                // 4. Location EditorID fallback
                if (location?.EditorID != null)
                {
                    foreach (var kvp in HoldCapitalPrefixes)
                    {
                        if (location.EditorID.StartsWith(kvp.Key, StringComparison.OrdinalIgnoreCase))
                            return (LocationCategory.Town, location);
                    }
                }

                return (LocationCategory.Unknown, null);
            }

        }
    }
}
